CV_Webbutveckling/Models/ErrorViewModel.cs
namespace CV_Webbutveckling.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CV_Webbutveckling/Controllers/AboutMeController.cs
using Microsoft.AspNetCore.Mvc;

namespace CV_Webbutveckling.Controllers
{
    public class AboutMeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Education()
        {
            return View();
        }

        public IActionResult Experience()
        {
            return View();
        }

    }
}

CV_Webbutveckling/Controllers/HomeController.cs
using CV_Webbutveckling.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CV_Webbutveckling.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CV_Webbutveckling/Views/AboutMe/Education.cshtml
@{
    ViewData["Title"] = "Education";
}
<h1 class="text-center" display-4>Utbildningar/Kurser</h1>

<ul class="mt-5">
    <li class="mt-5">
        .Net-utvecklare - YH
    </li>
    <li class="mt-5">
        NätverksTeknik - Komvux
    </li>
    <li class="mt-5">
        Flygtekniker - Gymnasiet
    </li>
    <li class="mt-5">
        Grundskola
    </li>
</ul>

CV_Webbutveckling/Views/AboutMe/Experience.cshtml
@{
    ViewData["Title"] = "Experience";
}
<h1 class="text-center display-4">Erfarenheter</h1>

<ul>
    <li class="mt-5">
        Lorem Ipsum
    </li>
    <li class="mt-5">
        Lorem Ipsum
    </li>
    <li class="mt-5">
        Lorem Ipsum
    </li>
    <li class="mt-5">
        Lorem Ipsum
    </li>
</ul>

CV_Webbutveckling/Views/AboutMe/Index.cshtml
@{
    ViewData["Title"] = "About me";
}
<h1 class="text-center display-5">Om mig</h1>

<dl class="ml-5 mt-5">
    <dt>Namn</dt>
    <dd>Jakob Zetterqvist</dd>
    <dt>Ålder</dt>
    <dd>29</dd>
    <dt>Bor i</dt>
    <dd>Tierp</dd>
    <dt>Språkkunskaper</dt>
    <dd>Svenska, Engelska</dd>
</dl>
<div class="d-flex justify-content-center">
    <img src="~/img/Porträtt.png" class="d-flex height="200" width="300" />
</div>

CV_Webbutveckling/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Välkommen!</h1>
    <p>Det här är en sida för att presentera mig, <span class="text-decoration-underline">Jakob Zetterqvist</span>.</p>
</div>

CV_Webbutveckling/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CV</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CV_Webbutveckling.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CV</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item navbar-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AboutMe" asp-action="Index">Om mig</a>
                        </li>
                        <li class="nav-item navbar-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AboutMe" asp-action="Education">Utbildningar/Kurser</a>
                        </li>
                        <li class="nav-item navbar-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AboutMe" asp-action="Experience">Erfarenhet</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CV - <a asp-area="" asp-controller="AboutMe" asp-action="Index">Om mig</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>